### ISSUE TITLE
Errores en add album

### ISSUE THREAD

**Issue by NicolasEzequielZulaicaRivera** [taller2-grupo5-rostov-1c2022/android-app#21]
- [x] el cover deberia salir como required
- [x] deberia haber un toast cuando falla
- [x] crashea si no tenes canciones para agregar
- [x] es raro que te cierra el modal mientras crea y despues lo vuelve a abrir

**Comment by fdelu** [comment]
@NicolasEzequielZulaicaRivera al final viste que pasó con el 4to? no lo pude reproducir, se arregló?

**Comment by NicolasEzequielZulaicaRivera** [comment]
En el celu no me pasa
